version: '3'

services:
  server1:
    build: .
    container_name: node-server-1
    environment:
      - PORT=5000
      - SERVER_ID=server1
    networks:
      - app-network

  server2:
    build: .
    container_name: node-server-2
    environment:
      - PORT=5000
      - SERVER_ID=server2
    networks:
      - app-network

  server3:
    build: .
    container_name: node-server-3
    environment:
      - PORT=5000
      - SERVER_ID=server3
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge