name: Deploy to Cloud Run

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Create ServiceAccountKey.json
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > ServiceAccountKey.json
      
      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/industrial-management-sy-6b3fd/industry-management-system-build-logs/build-logs/
      
      - name: Deploy to Cloud Run
        run: |
          # Create the env-vars.yaml file
          cat > env-vars.yaml << EOF
          FIREBASE_API_KEY: '${{ secrets.FIREBASE_API_KEY }}'
          FIREBASE_AUTH_DOMAIN: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'
          FIREBASE_PROJECT_ID: '${{ secrets.FIREBASE_PROJECT_ID }}'
          FIREBASE_STORAGE_BUCKET: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'
          FIREBASE_MESSAGING_SENDER_ID: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'
          FIREBASE_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'
          EOF
    
          # Deploy to Cloud Run
          gcloud run deploy industry-management-system \
            --image=gcr.io/industrial-management-sy-6b3fd/industry-management-system:${{ github.sha }} \
            --platform=managed \
            --region=asia-south2 \
            --port=5000 \
            --env-vars-file=env-vars.yaml \
            --allow-unauthenticated \
            --project=industrial-management-sy-6b3fd